//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class AspNetRole
{
    public AspNetRole()
    {
        this.AspNetUsers = new HashSet<AspNetUser>();
    }

    public string Id { get; set; }
    public string Name { get; set; }

    public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
}

public partial class AspNetUser
{
    public AspNetUser()
    {
        this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
        this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
        this.AspNetRoles = new HashSet<AspNetRole>();
    }

    public string Id { get; set; }
    public string Email { get; set; }
    public bool EmailConfirmed { get; set; }
    public string PasswordHash { get; set; }
    public string SecurityStamp { get; set; }
    public string PhoneNumber { get; set; }
    public bool PhoneNumberConfirmed { get; set; }
    public bool TwoFactorEnabled { get; set; }
    public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
    public bool LockoutEnabled { get; set; }
    public int AccessFailedCount { get; set; }
    public string UserName { get; set; }

    public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
    public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
    public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
}

public partial class AspNetUserClaim
{
    public int Id { get; set; }
    public string UserId { get; set; }
    public string ClaimType { get; set; }
    public string ClaimValue { get; set; }

    public virtual AspNetUser AspNetUser { get; set; }
}

public partial class AspNetUserLogin
{
    public string LoginProvider { get; set; }
    public string ProviderKey { get; set; }
    public string UserId { get; set; }

    public virtual AspNetUser AspNetUser { get; set; }
}

public partial class BILL
{
    public int Bill_ID { get; set; }
    public int OrderID { get; set; }
    public Nullable<System.DateTime> BillDate { get; set; }
    public string BillingAddress { get; set; }
    public string PaymentType { get; set; }
    public string CreditCardNo { get; set; }

    public virtual ORDER ORDER { get; set; }
}

public partial class C__MigrationHistory
{
    public string MigrationId { get; set; }
    public string ContextKey { get; set; }
    public byte[] Model { get; set; }
    public string ProductVersion { get; set; }
}

public partial class CART
{
    public int CartID { get; set; }
    public int RawID { get; set; }
    public int TotalPrice { get; set; }
    public int NumOfRM { get; set; }

    public virtual RAWMATERIAL RAWMATERIAL { get; set; }
}

public partial class CATEGORY
{
    public CATEGORY()
    {
        this.RAWMATERIALs = new HashSet<RAWMATERIAL>();
    }

    public int CategoryID { get; set; }
    public string cat_Name { get; set; }
    public byte[] CAT_image { get; set; }

    public virtual ICollection<RAWMATERIAL> RAWMATERIALs { get; set; }
}

public partial class CLIENT
{
    public CLIENT()
    {
        this.ORDERS = new HashSet<ORDER>();
        this.forgotpassword_client = new HashSet<forgotpassword_client>();
    }

    public int ClientID { get; set; }
    public string c_Fname { get; set; }
    public string c_Lname { get; set; }
    public string c_Gendre { get; set; }
    public string c_Address { get; set; }
    public string c_City { get; set; }
    public string c_ContactNo { get; set; }
    public string c_Email { get; set; }
    public string c_Username { get; set; }
    public string c_Password { get; set; }
    public Nullable<System.DateTime> c_RegisterDate { get; set; }

    public virtual ICollection<ORDER> ORDERS { get; set; }
    public virtual ICollection<forgotpassword_client> forgotpassword_client { get; set; }
}

public partial class forgotpassword_client
{
    public System.Guid id { get; set; }
    public Nullable<int> uid { get; set; }
    public Nullable<System.DateTime> requestdatetime { get; set; }

    public virtual CLIENT CLIENT { get; set; }
}

public partial class imageupload
{
    public int id { get; set; }
    public string Name { get; set; }
    public Nullable<int> size { get; set; }
}

public partial class ORDER
{
    public ORDER()
    {
        this.BILLs = new HashSet<BILL>();
        this.RAWMATERIALs = new HashSet<RAWMATERIAL>();
    }

    public int OrderID { get; set; }
    public int ClientID { get; set; }
    public Nullable<System.DateTime> OrderDate { get; set; }
    public Nullable<System.DateTime> RequiredDate { get; set; }
    public int TotalAmount { get; set; }

    public virtual ICollection<BILL> BILLs { get; set; }
    public virtual CLIENT CLIENT { get; set; }
    public virtual ICollection<RAWMATERIAL> RAWMATERIALs { get; set; }
}

public partial class RAWMATERIAL
{
    public RAWMATERIAL()
    {
        this.CARTs = new HashSet<CART>();
        this.ORDERS = new HashSet<ORDER>();
    }

    public int RawID { get; set; }
    public int CategoryID { get; set; }
    public string r_Name { get; set; }
    public string r_Description { get; set; }
    public Nullable<int> r_NeedQuantity { get; set; }
    public int r_Price { get; set; }
    public int r_QuantityInStock { get; set; }
    public string r_MinOrder { get; set; }
    public byte[] r_image1 { get; set; }
    public byte[] r_image2 { get; set; }
    public byte[] r_image3 { get; set; }
    public string r_imageid1 { get; set; }
    public int vendorID { get; set; }

    public virtual ICollection<CART> CARTs { get; set; }
    public virtual CATEGORY CATEGORY { get; set; }
    public virtual VENDOR VENDOR { get; set; }
    public virtual ICollection<ORDER> ORDERS { get; set; }
}

public partial class VENDOR
{
    public VENDOR()
    {
        this.RAWMATERIALs = new HashSet<RAWMATERIAL>();
    }

    public int VendorID { get; set; }
    public string v_Username { get; set; }
    public string v_Password { get; set; }
    public string Vname { get; set; }
    public string v_ContactNo { get; set; }
    public string v_Address { get; set; }
    public string v_City { get; set; }
    public string v_Email { get; set; }
    public System.DateTime v_RegisterDate { get; set; }

    public virtual ICollection<RAWMATERIAL> RAWMATERIALs { get; set; }
}

public partial class getproduct_Result
{
    public byte[] r_image1 { get; set; }
    public string r_Name { get; set; }
    public int r_Price { get; set; }
}
